# Generated by Django 6.0.6 on 2026-07-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_id",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
