# Generated by Django 6.0.6 on 2026-07-02 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "point",
                    models.CharField(
                        help_text="Укажите место", max_length=100, verbose_name="Место"
                    ),
                ),
                (
                    "time",
                    models.TimeField(help_text="Укажите время", verbose_name="Время"),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие",
                        max_length=500,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "nice_habit",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Укажите признак приятности",
                        null=True,
                        verbose_name="Признак приятности",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Укажите периодичность",
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "award",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение",
                        max_length=100,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=120,
                        help_text="Укажите время на выполнение в секундах",
                        null=True,
                        verbose_name="Время на выполнение в секундах",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True,
                        help_text="Укажите признак публичности",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите автора",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "tied_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите связанную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
